### ISSUE TITLE
Wallpaper Image

### ISSUE THREAD

**Issue by matt-shepherd** [datalogic/dxu#6]
Hi,

The documentation mentions enabling Binary transfer for setting the wallpaper image etc..  however for the life of me, i cant work out how i can set a device's wallpaper either using DXU or Scan2Deploy for onboarding new devices?

Thanks

**Comment by codybrookshear** [comment]
Hi Matt,

Sorry for the delay in getting back to you. 

We used to offer that ability in DXU but unfortunately it had to be removed for technical reasons. I just went and updated datalogic.github.io to remove references to that. But we do think this is a good idea to offer this feature in Scan2Deploy Studio. I don't have a timeline for you, but it's on our list.

Thank you,
Cody
